before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.0
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - ./node_modules

env:
  - NODE_ENV=development

language: node_js

node_js:
  - 12
  - 10

dist: trusty
sudo: false

branches:
  only:
    - master

install:
  - yarn install

script:
  - yarn pull-request
